#!/bin/bash
cargo build --target=armv7-unknown-linux-gnueabihf
scp target/armv7-unknown-linux-gnueabihf/debug/neo_eink simson@nanopi:bin
#scp target/armv7-unknown-linux-gnueabihf/debug/neo_eink honeypot:
