[package]
name = "neo_eink"
version = "0.2.0"
authors = ["Fredrik Simonsson"]
edition = "2021"

[dependencies]
linux-embedded-hal = "0.4.0"
# nb = "0.1.1"
nix = "0.29.0"
epd-waveshare = "0.6.0"
embedded-graphics = "0.8.1"
sysfs_gpio = "0.6.2"
clap = "4.5.20"
input-stream = "0.4.0"
embedded-hal = "1.0.0"
